project_id = "zkgvvuyubalbymhfxrex"

[functions.collect]
verify_jwt = false

[functions.identify]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.sync-klaviyo]
verify_jwt = false

[functions.process-events]
verify_jwt = false

[functions.webhooks-shopify]
verify_jwt = false